source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# CocoaPods for iOS dependency management
gem 'cocoapods', '~> 1.16'
gem 'activesupport', '>= 6.1.7.5', '< 8.0'

# Fastlane for iOS deployment automation
gem 'fastlane'
